/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminMeetRouteImport } from './routes/admin.meet'
import { Route as RoomRoomIdIndexRouteImport } from './routes/room/$roomId/index'
import { Route as RoomRoomIdLobbyRouteImport } from './routes/room/$roomId/lobby'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMeetRoute = AdminMeetRouteImport.update({
  id: '/admin/meet',
  path: '/admin/meet',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdIndexRoute = RoomRoomIdIndexRouteImport.update({
  id: '/room/$roomId/',
  path: '/room/$roomId/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdLobbyRoute = RoomRoomIdLobbyRouteImport.update({
  id: '/room/$roomId/lobby',
  path: '/room/$roomId/lobby',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/admin/meet': typeof AdminMeetRoute
  '/room/$roomId/lobby': typeof RoomRoomIdLobbyRoute
  '/room/$roomId/': typeof RoomRoomIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/admin/meet': typeof AdminMeetRoute
  '/room/$roomId/lobby': typeof RoomRoomIdLobbyRoute
  '/room/$roomId': typeof RoomRoomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/admin/meet': typeof AdminMeetRoute
  '/room/$roomId/lobby': typeof RoomRoomIdLobbyRoute
  '/room/$roomId/': typeof RoomRoomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/terms' | '/admin/meet' | '/room/$roomId/lobby' | '/room/$roomId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/terms' | '/admin/meet' | '/room/$roomId/lobby' | '/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/terms'
    | '/admin/meet'
    | '/room/$roomId/lobby'
    | '/room/$roomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TermsRoute: typeof TermsRoute
  AdminMeetRoute: typeof AdminMeetRoute
  RoomRoomIdLobbyRoute: typeof RoomRoomIdLobbyRoute
  RoomRoomIdIndexRoute: typeof RoomRoomIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/meet': {
      id: '/admin/meet'
      path: '/admin/meet'
      fullPath: '/admin/meet'
      preLoaderRoute: typeof AdminMeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId/': {
      id: '/room/$roomId/'
      path: '/room/$roomId'
      fullPath: '/room/$roomId/'
      preLoaderRoute: typeof RoomRoomIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId/lobby': {
      id: '/room/$roomId/lobby'
      path: '/room/$roomId/lobby'
      fullPath: '/room/$roomId/lobby'
      preLoaderRoute: typeof RoomRoomIdLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TermsRoute: TermsRoute,
  AdminMeetRoute: AdminMeetRoute,
  RoomRoomIdLobbyRoute: RoomRoomIdLobbyRoute,
  RoomRoomIdIndexRoute: RoomRoomIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
